<Project>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>Carubbi</Authors>
    <Company>Carubbi</Company>
    <Product>Carubbi.AudioConverter</Product>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <RepositoryUrl>https://github.com/rcarubbi/Carubbi.AudioConverter.Api</RepositoryUrl>
  </PropertyGroup>

</Project>
